### ISSUE TITLE
Why are the path prefix needed with NG CLI?

### ISSUE THREAD

**Issue by Vad1mo** [vmware/clarity-seed#23]
Is not very clear to me why do the references in `@Components` need since 0.8.0 the local path prefix `./` like in in `templateUrl: './app.component.html'`. As I see it it only affects the NG CLI Branch.

Changes in this commit 
https://github.com/vmware/clarity-seed/commit/ef655e8487e33b992f530608221715f182105742

or this pull request:
https://github.com/vmware/clarity-seed/pull/17

**Comment by Shijir** [comment]
Yes, Angular-CLI used to work fine with specifying just file names in the style or templateUrls properties. But one of their recent changes introduced the following error: `Module not found: ...` if you don't prepend `./`. I think they are fixing the issue in https://github.com/angular/angular-cli/issues/3838 so it will be more flexible meaning you can use both the old and new ways of specifying the component-relative files. For example, both of them will be allowed `templateUrl: './app.component.html'` and `templateUrl: 'app.component.html'`
