### ISSUE TITLE
Fresh clone fails AOT Build

### ISSUE THREAD

**Issue by Nusinov212** [vmware/clarity-seed#25]
Issue: a fresh clone of this seed fails to AOT build, maybe a dependency issue? Totally possible this is just an issue with my local dev env (Not a local admin).
Steps to reproduce:
1) clone
2) run yarn install
3) run ng build --aot --prod

Versions:
node - v6.5.0
npm - 3.10.3
OS - win 7

Error:
E:\Projects\cseed>ng build --aot
Hash: dfa4f0fa9307848b42e6
Time: 9552ms
chunk    {0} scripts.bundle.js, scripts.bundle.map (scripts) 262 kB {4} [initial] [rendered]
chunk    {1} styles.bundle.js, styles.bundle.map (styles) 785 kB {4} [initial] [rendered]
chunk    {2} main.bundle.js, main.bundle.map (main) 1.74 kB {3} [initial] [rendered]
chunk    {3} vendor.bundle.js, vendor.bundle.map (vendor) 1.06 MB [initial] [rendered]
chunk    {4} inline.bundle.js, inline.bundle.map (inline) 0 bytes [entry] [rendered]

ERROR in Error encountered resolving symbol values statically. Calling function 'NoOpAnimationDriver', function calls are not supported. Consider repl
acing the function or lambda with a reference to an exported function, resolving symbol AnimationDriver.NOOP in E:/Projects/cseed/node_modules/@angula
r/platform-browser/src/dom/animation_driver.d.ts, resolving symbol BrowserTestingModule in E:/Projects/cseed/node_modules/@angular/platform-browser/te
sting/browser.d.ts, resolving symbol BrowserTestingModule in E:/Projects/cseed/node_modules/@angular/platform-browser/testing/browser.d.ts

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in 'E:\Projects\cseed\src'
 @ ./src/main.ts 5:29-76
 @ multi main

ERROR in ./~/@angular/core/src/linker/system_js_ng_module_factory_loader.js
Module not found: Error: Can't resolve 'E:\Projects\cseed\src\$$_gendir' in 'E:\Projects\cseed\node_modules\@angular\core\src\linker'
 @ ./~/@angular/core/src/linker/system_js_ng_module_factory_loader.js 69:15-36 85:15-102
 @ ./~/@angular/core/src/linker.js
 @ ./~/@angular/core/src/core.js
 @ ./~/@angular/core/index.js
 @ ./src/main.ts
 @ multi main

**Comment by Shijir** [comment]
Hi @Nusinov212, I think your issue is related to this one: https://github.com/angular/angular/issues/13624. 

Basically, it says `test.ts` shouldn't be included in the compilation. So please add `test.ts` in the `exclude` field of the tsconfig.ts like this:

```
"exclude": [
        "node_modules",
        "dist",
        "test.ts"
    ]
```

I have also posted PR for excluding `test.ts` in https://github.com/vmware/clarity-seed/pull/26
