### ISSUE TITLE
Ng-CLI Production build "out of the box" too big

### ISSUE THREAD

**Issue by neoswf** [vmware/clarity-seed#31]
Correct me if I'm wrong, but running `ng serve --prod` (which run `ng build --prod` as well) generates a **dist** folder which contains 12 mg files size.

Looking at the files, and I find that Vendor[s] files are mainly the one which are responsible for that size.

1.  What is the best way to customize and reduce it?
2. Is there an already built in method to do so?
3. Am I searching in the wrong place and I actually need to search at Angular-CLI?

Thank you.

**Comment by neoswf** [comment]
I have advanced and ran `ng build -prod -sm=false --vendor-chunk=false` to remove vendor and map files, and the build size dropped from 12.3mg to 2.4mb. 

Still doesn't make sense that Out of the Box the project weight that much.

I love the look and feel of the project's design. I hope some prod dependencies are not needed, to be able to reduce the size.

**Comment by Shijir** [comment]
I recommend you to use the ahead of time compilation for production, which generates a build with a size of 2.2mb (that is including `.gz` pre-gzipped files).

**Comment by neoswf** [comment]
Hey @Shijir. Thank you for your answer.
I am new to NG2 (& AOT feature), and I started reading about and discovered more regarding it, for example, the Tree Shaking feature.
So I wondered how come the `dist` folder weight so much, but it has "duplicated files" like `*.js` & `*.js.gz`, so I decided to test the app, on my localhost, against my inspector.

The results impressed me.

First I tried running the max settings for AOT. I ran `ng serve` with AOT & prohibited SourceMap & Vendor files from being built - `--aot=true -prod -sm=false —vendor-chunk=false` 

<img width="673" alt="screen shot 2017-01-24 at 19 37 02" src="https://cloud.githubusercontent.com/assets/82842/22269058/f9060ba0-e270-11e6-9aa3-cb1905a26b81.png">

Then, as I read that AOT has the TreeShaking feature, I guessed that its not necessary, so I tried to see what will happen if ill only run AOT configuration

<img width="674" alt="screen shot 2017-01-24 at 19 40 13" src="https://cloud.githubusercontent.com/assets/82842/22269059/f9091c50-e270-11e6-947b-cf6ba5d106b3.png">

Than I decided to see what will be the result of running `--prod` configuration only

<img width="675" alt="screen shot 2017-01-24 at 19 43 02" src="https://cloud.githubusercontent.com/assets/82842/22269061/f90c2184-e270-11e6-96a6-588c9a6cb2ef.png">

And last - serving the app in development mode

<img width="673" alt="screen shot 2017-01-24 at 19 46 30" src="https://cloud.githubusercontent.com/assets/82842/22269060/f90bf6be-e270-11e6-823b-0a8928a5c4b2.png">

As you can see:

- `ng serve --aot=true -prod -sm=false —vendor-chunk=false` - 444kb, 14 requests, 1.04 seconds
- `ng serve --aot=true -prod` - 445kb, 15 requests, 1.02 seconds
- `ng serve -prod` - 514kb, 15 requests, 2.36 seconds
- `ng serve ` - 5.3MB, 14 requests, 2.57 seconds

Conclusion: AOT is an amazing feature. `Dist` folder's size doesn't tells all the truth. AOT is an amazing and unbelievable feature. Thanks for https://github.com/angular/angular-cli for making so goddamn easy to implement and execute.
