### ISSUE TITLE
When are you updating 0.8.7 with latest component updates?

### ISSUE THREAD

**Issue by wknet123** [vmware/clarity-seed#36]

**Comment by Shijir** [comment]
Sorry, your question is not very clear to me. Users themselves can update the versions of Clarity modules such as `clarity-angular`, `clarity-ui`, and `clarity-icons` in this seed application, which is just a sample angular application that makes use of the aforementioned Clarity modules.

**Comment by Shijir** [comment]
Closing this issue as this have been inactive.
