### ISSUE TITLE
Seed not compatible with Angular 4.0

### ISSUE THREAD

**Issue by meije702** [vmware/clarity-seed#46]
I am a bit new to this but the current version is not compatible with Angular 4.0 due to the Animation thing. As copied from the angular upgrade guide:

> If you use animations in your application, you should import BrowserAnimationsModule from @angular/platform-browser/animations in your App NgModule.

So I update my own code, its actually fairly straightforward and everything is running fine now.
I have made my own branch and pushed my local updates to my own branch here on GIT.
Is there some way I can share this with you guys? (sorry worked with TFS all my life, I don't know how this works and I don't want to brake anything)

**Comment by tgeorgiev** [comment]
@meije702 I see you already forked the seed project. You can make the commit in your repo, push it and then create a pull request for it. See here https://help.github.com/articles/creating-a-pull-request-from-a-fork/

**Comment by meije702** [comment]
Excuses for the late reaction, I think we can close this one as it is now fixed with the latest 0.9 release, thanks!

**Comment by mathisscott** [comment]
Thanks @meije702!
