### ISSUE TITLE
Form validation tooltips causing input to not render

### ISSUE THREAD

**Issue by BlakeDraper** [vmware/clarity-seed#52]
There seem to be a bug with the way form validation works using tooltips in the examples. I have found this issue in both the [form validation example code](https://vmware.github.io/clarity/documentation/input-fields) and the [reactive forms example code](https://vmware.github.io/clarity/documentation/forms). The input does not render when following the example code. Through trial and error I discovered that removing the `class="tooltip tooltip-validation tooltip-sm" ` attribute from the label causes the input to show up and be useable, but of course that removes visual validation warnings with the tooltips. 

This image shows the output of the example code, with the inputs not rendering:
![formvalidbug](https://cloud.githubusercontent.com/assets/6978380/25549511/df908108-2c37-11e7-9288-5710a4909cb0.PNG)

This is what happens after removing `class="tooltip tooltip-validation tooltip-sm" `: 
![formvalidbug2](https://cloud.githubusercontent.com/assets/6978380/25549575/4736fddc-2c38-11e7-9906-a3b51efbe38e.PNG)

As you can see, input appears and text can be entered. I am not sure if this is a bug or something I am perhaps missing with the loading of the clarity css. I am using the seed so I assume everything should be in place. I am using the angular cli to serve, and I do have the following references within the styles object of angular-cli.json:
```
"../node_modules/clarity-icons/clarity-icons.min.css",
"../node_modules/clarity-ui/clarity-ui.min.css",
```
I would like to use the forms validation as it appears in the documentation examples, but there seems to be a bug somewhere. Thanks, required info below.

**_Instruction on how to replicate the issue_**

Insert the[ form validation example code](https://github.com/vmware/clarity/tree/6536b1156ea729c682e183ba3bd3807c2cc95461/src/app/forms/form-validation-static) from the [Clarity Documentation](https://vmware.github.io/clarity/documentation/input-fields#top)

run `ng serve`

**_The version number of Angular_**
4.0.1

**_The version number of Clarity_**
 clarity-angular: 0.9.2
 clarity-icons: 0.9.0
 clarity-ui: 0.9.0

**_The version number of Node_**
7.4.0

**_The browser name and version number_**
Google Chrome version 58.0.3029.81

**_The OS running the seed_**
Windows 7

**Comment by Shijir** [comment]
Hi @BlakeDraper, what was the reason you wanted to remove those classes? I see that you are using form validation markup, but at the same time, you want to remove the validation tooltip classes. So I am guessing `Form Validation` markup might be not for your use case? If your goal was to remove validation warning, you need to remove only `invalid` class from the label.

**Comment by BlakeDraper** [comment]
@Shijir  I don't want to remove those classes. I very much want those classes and the validation visual they provide. What I am saying is the input is not rendering in the Clarity example code in the context of the clarity-seed codebase, and I went through a process of isolating potential causes and found that removing them makes it work correctly. So I am pointing out that something with those seems to be corrupting the DOM rendering. Perhaps I am doing something wrong - I'll happily take guidance.

Also I neglected to mention in the original issue that there are no error messages in the console when this behavior (input not rendering) occurs.

**Comment by BlakeDraper** [comment]
Fresh after a weekend away from it, I discovered an error in my html template file. The labels and inputs were not within a div with the `.card-text` class. Once I put them inside a div with that class, inputs rendered appropriately. You can consider this a closed issue - I apologize if I wasted any of your time.

**Comment by mathisscott** [comment]
Thanks for the update, @BlakeDraper
