### ISSUE TITLE
Please upgrade `karma-remap-istanbul` lib.

### ISSUE THREAD

**Issue by Twiknight** [vmware/clarity-seed#53]
The `karma-remap-istanbul` imported is out of date. 

run unit tests with `--code-coverage` will result in error 

```
Error: Could not find source map for: "path/to/clarity-seed/src/test.ts"
```
and you will get incomplete coverage reports.

It is a know issue of lib `remap-istanbul`

 see this pr: 
https://github.com/angular/angular-cli/issues/883#issuecomment-221076483

**Comment by mathisscott** [comment]
@shijir / @jeeyun : is this something we want to do for clarity-seed?

**Comment by hippee-lee** [comment]
This package was updated as part of https://github.com/vmware/clarity-seed/pull/60 
Where several `dev-deps` were upgraded along with `karma-remap-istanbul.

Please let me know if you still have this problem with the seed.
