### ISSUE TITLE
ng g component failed

### ISSUE THREAD

**Issue by l770943527** [vmware/clarity-seed#54]
I run this cmd "ng g component component1 "
below is what I got. I have install angular-cli global again, but still got the same error.
Could u help me with that, thanks : )
------------------------
As a forewarning, we are moving the CLI npm package to "@angular/cli" with the next release,
which will only support Node 6.9 and greater. This package will be officially deprecated
shortly after.

To disable this warning use "ng set --global warnings.packageDeprecation=false".

You have to be inside an angular-cli project in order to use the generate command.

**Comment by Shijir** [comment]
Hi @l770943527, does your environment meet the prerequisite of Angular CLI? 
>Both the CLI and generated project have dependencies that require Node 6.9.0 or higher, together with NPM 3 or higher. 

Check your angular/cli version by running `ng -v` or `ng version`.

**Comment by l770943527** [comment]
Thanks a lot! I have solved my problem following your steps. : )
