### ISSUE TITLE
Package.json incorrect

### ISSUE THREAD

**Issue by cgarveyie** [vmware/clarity-seed#56]
Hi there,

Tried to run npm install on the seed but hit a few roadblocks.
`verbose stack Error: Error extracting C:\Users\paperspace\AppData\Roaming\npm-cache\clarity-angular\0.9.4\package.tgz archive: ENOENT: no such file or directory, open 'C:\Users\paperspace\AppData\Roaming\npm-cache\clarity-angular\0.9.4\package.tgz'`

The same thing happens with the clarity-icons and clarity-ui directories in npm-cache.

The root cause appears to be that a 0.9.5 directory is being created, but the package expects 0.9.4

**Comment by hippee-lee** [comment]
Hi @cgarveyie, 

Are you still experiencing this?

Our package.json is set up to use the latest minor and patch version
```    
    "clarity-angular": "^0.9.0",
    "clarity-icons": "^0.9.0",
    "clarity-ui": "^0.9.0",
```

For me this was installing 0.9.16 as of today.

**Comment by hippee-lee** [comment]
I am not able to recreate this, please re-open the issue if you continue to experience this issue.
