### ISSUE TITLE
Can not add custom Clarity Icon

### ISSUE THREAD

**Issue by WuglyakBolgoink** [vmware/clarity-seed#63]
Hi,

I try to change my App-Logo via:

```js
import {ClarityIcons} from 'clarity-icons';
export class AppComponent {
    constructor() {

         ClarityIcons.add({'my-logo': '<svg>blablabla</svg>'}); 

  }
}

```

but it doesn't work...

if I check icon =>`console.log('ICON myLogo ==>', ClarityIcons.get('my-logo'));` => SUCCESS, I see svg code.

but I see error in console too `Error: 'my-logo' is not found in the Clarity Icons set.`

![bildschirmfoto 2017-10-08 um 18 05 52](https://user-images.githubusercontent.com/2271337/31318455-64b7d6c4-ac53-11e7-98a7-1f9d21626544.png)

i found same issue https://github.com/vmware/clarity/issues/689#issuecomment-326740446 and this trick doesn't work too. If I remove `clarity-icons.min.js` from `cli.json` i see only  half part of icons... O_o

PS: 
```json
"dependencies": {
    "@angular/animations": "^4.4.4",
    "@angular/common": "^4.4.4",
    "@angular/compiler": "^4.4.4",
    "@angular/core": "^4.4.4",
    "@angular/forms": "^4.4.4",
    "@angular/http": "^4.4.4",
    "@angular/platform-browser": "^4.4.4",
    "@angular/platform-browser-dynamic": "^4.4.4",
    "@angular/router": "^4.4.4",
    "@ngx-translate/core": "^8.0.0",
    "@ngx-translate/http-loader": "^2.0.0",
    "@webcomponents/custom-elements": "^1.0.4",
    "angular-star-rating": "^3.0.8",
    "angular2-notifications": "^0.7.8",
    "clarity-angular": "^0.10.8",
    "clarity-icons": "^0.10.8",
    "clarity-ui": "^0.10.8",
    "core-js": "^2.5.1",
    "font-awesome": "^4.7.0",
    "lodash": "^4.17.4",
    "mutationobserver-shim": "^0.3.2",
    "rxjs": "^5.4.3",
    "ts-helpers": "^1.1.2",
    "web-animations-js": "^2.3.1",
    "zone.js": "^0.8.18"
  },
  "devDependencies": {
    "@angular/cli": "^1.4.5",
    "@angular/compiler-cli": "^4.4.4",
    "@types/core-js": "^0.9.43",
    "@types/jasmine": "^2.6.0",
    "@types/jasminewd2": "^2.0.3",
    "@types/node": "^8.0.33",
    "bootstrap": "^4.0.0-beta",
    "codelyzer": "^3.2.1",
    "enhanced-resolve": "^3.4.1",
    "jasmine-core": "^2.8.0",
    "jasmine-spec-reporter": "^4.2.1",
    "karma": "^1.7.1",
    "karma-chrome-launcher": "^2.2.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-mocha-reporter": "~2.2.1",
    "karma-remap-istanbul": "~0.6.0",
    "protractor": "~5.1.2",
    "ts-node": "^3.3.0",
    "tslint": "^5.7.0",
    "typescript": "^2.5.3",
    "typings": "^2.1.1",
    "webdriver-manager": "^12.0.6"
  }
```

what do I wrong?

**Comment by mathisscott** [comment]
Are you also loading ClarityIcons on your index page? My first guess is that you are double loading it.

**Comment by hippee-lee** [comment]
Hi @WuglyakBolgoink - are you still experiencing this issue?

**Comment by WuglyakBolgoink** [comment]
I have default settings from clarity-seed :)

**Comment by hippee-lee** [comment]
Hey there, I tried using a fresh checkout of the clarity-seed and was able to add icons without any errors. At this point I can't recreate your issue and am not sure what steps to take to see the error you are reporting. 

Can you replicate this issue in a repository that you can share? If you can, feel free to reopen the issue with a link to the repo so I can take a look.

**Comment by darrenmothersele** [comment]
Sorry to comment on a closed post. But for information, I've had the same issue.
@WuglyakBolgoink the only way I could get it to work was to add the icon in `polyfills.ts`

**Comment by WuglyakBolgoink** [comment]
> import {ClarityIcons} from 'clarity-icons';


should not be loaded in controller. `ClarityIcons` is on global scope.

ticket can be closed. tested with v0.11.1.
