### ISSUE TITLE
How to test clr-modal?

### ISSUE THREAD

**Issue by timvl** [vmware/clarity-seed#65]
Please add a jasmine test in `about.component.spec.ts` that demonstrates how to test a clarity modal.

**Comment by hippee-lee** [comment]
Hi @timvl are you asking how we would approach testing the use of a [Clarity Modal](https://vmware.github.io/clarity/documentation/modals) in an application or about the unit tests we already run on the modal component? If you are looking for that they can be found here: https://github.com/vmware/clarity/blob/master/src/clarity-angular/modal/modal.spec.ts

**Comment by hippee-lee** [comment]
@timvl - any updates on this? Did my comment above help?

**Comment by timvl** [comment]
Hi, I’ve found the test cases you referred to. Thanks!
