### ISSUE TITLE
ng serve doesn't find the project

### ISSUE THREAD

**Issue by prydin** [vmware/clarity-seed#74]
I followed the instructions in the README. When I get to the "ng serve" step, it's telling me I can't start it because I'm not in a project directory. I'm in the top directory of the "clarity-seed" tree I get when I'm extracting.

OS: Amazon CentOS7.
Node version:  v6.9.1
Angular-CLI version: 1.6.7

Output:
[centos@xxxxx ~]$ git clone https://github.com/vmware/clarity-seed.git
Cloning into 'clarity-seed'...
remote: Counting objects: 441, done.
remote: Total 441 (delta 0), reused 0 (delta 0), pack-reused 441
Receiving objects: 100% (441/441), 515.64 KiB | 0 bytes/s, done.
Resolving deltas: 100% (259/259), done.
[centos@xxxxx ~]$ cd clarity-seed
[centos@xxxxx clarity-seed]$ yarn
yarn install v1.3.2
info No lockfile found.
[1/4] Resolving packages...
warning karma-remap-istanbul > remap-istanbul > gulp-util@3.0.7: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
warning typings@1.5.0: Typings is deprecated in favor of NPM @types -- see README for more information
[2/4] Fetching packages...
info fsevents@1.1.3: The platform "linux" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > @angular/compiler-cli@5.0.5" has incorrect peer dependency "typescript@>=2.4.2 <2.5".
warning "@angular/compiler-cli > tsickle@0.24.1" has incorrect peer dependency "typescript@2.4.2".
warning " > codelyzer@3.1.2" has incorrect peer dependency "@angular/compiler@^2.3.1 || >=4.0.0-beta <5.0.0".
warning " > codelyzer@3.1.2" has incorrect peer dependency "@angular/core@^2.3.1 || >=4.0.0-beta <5.0.0".
[4/4] Building fresh packages...
success Saved lockfile.
Done in 33.21s.
[centos@xxxxx clarity-seed]$ ng serve
As a forewarning, we are moving the CLI npm package to "@angular/cli" with the next release,
which will only support Node 6.9 and greater. This package will be officially deprecated
shortly after.

To disable this warning use "ng set --global warnings.packageDeprecation=false".

You have to be inside an angular-cli project in order to use the serve command.
[centos@xxxxx clarity-seed]$

**Comment by hippee-lee** [comment]
1. Can you confirm that you are using `@angular/cli` and not `angular-cli`? 
2. Can you confirm that `@angular/cli` is **only** installed locally to the project and **not globally** on the system?

**Comment by richardthombs** [comment]
@hippee-lee isn’t it standard practice to have the cli installed globally as well as locally?

**Comment by hippee-lee** [comment]
Yes, but I'm trying to see if the issue is b/c of one having `angular-cli` and another having `@angular/cli` to eliminate a conflict between the two.

**Comment by prydin** [comment]
It was a version issue. I was sure I had the right version of angular-cli, but I checked it in the wrong window... Classic mistake. Closing.
